### ISSUE TITLE
StoreObservable should probably expose `get`

### ISSUE THREAD

**Issue by agubler** [dojo/interfaces#37]
**Enhancement**

`StoreObservable` should probably expose `get` and potentially other store methods.

Package Version: Latest

**Comment by lzhoucs** [comment]
@maier49 can correct me if I am wrong, I think [`StoreObservable` in this repo](https://github.com/dojo/interfaces/blob/master/src/abilities.d.ts#L87-L93) is a bit out dated because it is not used anywhere else, and `dojo/stores` has a [separate `StoreObservable`](https://github.com/dojo/stores/blob/master/src/store/createStoreObservable.ts#L13) used across the repo.

We can either cleanup `StoreObservable` in this repo, or move the `dojo/stores` one into this repo. Since it is not used anywhere else, cleanup might be a better option.

On the other hand, all the essential store operations are defined in the [`Store` interface](https://github.com/dojo/stores/blob/master/src/store/createStore.ts#L51-L63) in the current implementation.

**Comment by maier49** [comment]
The `StoreObservable` in `dojo/stores` is serving an entirely different purpose than this one. I actually think that it would make more sense for `StoreObservable` and `StorePatchable` here to be called `ObservableStore` and `PatchableStore`. That would be more consistent with the other interfaces like `ActionableOptions` and `RenderableParent`. Judging from the [stated purpose of these interfaces](https://github.com/dojo/interfaces/blob/master/src/abilities.d.ts#L1-L6) I'm not sure we would want to get rid of it or replace it with one from `dojo/stores`.

**Comment by lzhoucs** [comment]
Thanks for the input @maier49 , I agree that the rename would make it more consistent, and help clear some of the confusions between it and the one in `dojo/stores`

After digging this a bit more, I do find some usage of `StoreObservablePatchable`(which is an intersection of `StoreObservable` and `StorePatchable`). It seems we recently replaced `ObservableState` with it in https://github.com/dojo/compose/pull/109, which brings up a question for @agubler : do we really want to expose store operations in `StoreObservable` if it replaces `ObservableState` which only has two operations: `observe` and `patch`, as documented in the [Widget System doc](https://github.com/dojo/meta/blob/master/documents/Widget-System.md#observing-and-updating-state). If so I might need some potential use cases of those store operations to help me get started.

It might also bring up a side issue for `dojo/stores`: Although the two `StoreObservable` are serving different purposes, it seems the store has to 'implement' the `StoreObservable` defined in this repo, because the `ObservableState`(or the repurposed `StoreObservablePatchable`) forces the store instance to have the ability to observe by id. In other words, [createObservableStoreMixin](https://github.com/dojo/stores/blob/master/src/store/mixins/createObservableStoreMixin.ts) can not be an optional mixin for store, because `observe` always needs to be available for a dojo 2 application to work. as mentioned in [Widget System doc](https://github.com/dojo/meta/blob/master/documents/Widget-System.md),
>The ObservableState interface are the part of the Dojo 2 store API that are needed to manage the state.

On the other hand, if we have `observe` built into the store just like `patch`, we could help avoid some boilerplate code for users when [creating an observable store](https://github.com/dojo/examples/blob/master/todo-mvc/src/stores/createObservableStore.ts).

**Comment by agubler** [comment]
@lzhoucs right not the interface effectively describes a store with the minimal API required to be used as `stateFrom`, with `patch` and `observe(id)` being mandatory - I honestly cannot remember the reasoning behind me raising this issue* but I don't see adding `get` as an issue because frankly all the implementations that are passed will implement `get(id)`.

*note to self put more information on issues in future.
