### ISSUE TITLE
Move widgetBases to widgets

### ISSUE THREAD

**Issue by agubler** [dojo/interfaces#41]
These interfaces are not used by anything other than widgets so would make sense to move them to the widgets package.

**Comment by kitsonk** [comment]
We just need to make sure that any cross-cutting concerns are properly represented in `Renderable`... which also means that we may need `RenderableContainer` eventually too, because the public API would change for something like `app`... Of course, properly refactoring `app` and `actions` to take advantage of the interfaces would ensure that you are properly removing things that don't have any cross cutting concerns.
